clear all
clc
D=input('Enter the length of the transmission line')
if(D<=50)
    r=input('Enter the value of resistance')
    X=input('Enter the inductive resistance')
    Vr=input('Enter the receiving end voltage')
    Pr=input('Enter the receiving end power')
    Pfr=input('Enter the receiving end powerfactor')
    Ir=Pr/(Vr*Pfr)
    a=cos(Pfr)
    Vs=Vr+(Ir*r*Pfr)+(Ir*X*sin(a))
    Pfs=((Vs*Pfr)+(Ir*r))/Vs;
    reg=(((abs(Vs)-abs(Vr))*100)/abs(Vr))
    loss=(Ir^2*r)
    eff=(Pr/(Pr+loss))*100
elseif(D>50 && D<=100)
    r=input('Enter the value of resistance')
    X=input('Enter the inductive resistance')
    Y=input('Enter the susceptance in  mho')
     Vr=input('Enter the receiving end voltage')
    Pr=input('Enter the receiving end power')
    Pfr=input('Enter the receiving end powerfactor')
    Vr1=(Vr/(3^(0.5)))
    Ir=(Pr/(3^(1/2)*Vr*Pfr))
    a=Pfr
    b=sqrt(1-(Pfr^2))
    Irc=(Pfr-b*i)
    Ir1=Ir*Irc
    Z=r+(i*X)
    Ic1=(i*Vr1*Y)/2
    I1=Ir1+Ic1
    Vs=Vr1+(I1*Z)
    Ic2=(i*Vs*Y)/2
    Is=I1+Ic2
    d=radtodeg(angle(Vr))-radtodeg(angle(Vs))
    c=radtodeg(angle(Vr))- radtodeg(angle(Is))
    Pfa=c-d
    Pfs=cos(Pfa)
    reg=((abs(Vr1)-abs(Vs))/abs(Vs))*100
    Ps=3*abs(Vs)*abs(Is)*Pfs
    eff=(Pr/Ps)*100
elseif(D>100)
    r=input('Enter the value of resistance')
    X=input('Enter the inductive resistance')
    Y=input('Enter the susceptance in  mho')
     Vr=input('Enter the receiving end voltage')
    Pr=input('Enter the receiving end power')
    Pfr=input('Enter the receiving end powerfactor')
    Z=r+(i*X)
    Vr1=(Vr/(3^(0.5)))
    Ir=(Pr/(3^(0.5)*Vr*Pfr))
    a1=1+((Y*Z)*(0.5))+(Y*Y*Z*Z*(1/24))
    b1=((Y*Z)^(0.5))+((Y*Z)^(3/2)/6)
    Vs=(Vr1*a1)+(Ir*b1*(Z/Y)^(0.5))
    Is=(Vr1*(Y/Z)^(0.5)*b1)+(Ir*a1)
    Pfs=cosd((radtodeg(angle(Vs)))-radtodeg(angle(Is)))
    Ps=3*abs(Vs)*abs(Is)*Pfs
    reg=((abs(Vs)-abs(Vr1))/abs(Vr1))*100
    eff=(Pr/Ps)*100
end